[project]
name = "pybleau"
version = "0.1.0"
description = "A Python wrapper for Tableau's REST and Metadata APIs."
readme = "README.md"
requires-python = ">=3.7"
license = {text = "MIT"}
dependencies = [
    "requests",
    "click",
    "graphql-core",
]

# If you are dynamically generating some fields:
dynamic = ["readme", "requires-python"]
[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
